-- Rode este SQL no Supabase: SQL Editor > New query > Run

create table if not exists public.lancamentos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  area text not null check (area in ('Matemática', 'Natureza', 'Humanas', 'Linguagens')),
  quantidade integer not null check (quantidade > 0),
  descricao text not null,
  materia text,
  criado_em timestamptz not null default now()
);

alter table public.lancamentos enable row level security;

create policy "Usuário vê apenas seus lançamentos"
on public.lancamentos for select
using (auth.uid() = user_id);

create policy "Usuário cria apenas seus lançamentos"
on public.lancamentos for insert
with check (auth.uid() = user_id);

create policy "Usuário exclui apenas seus lançamentos"
on public.lancamentos for delete
using (auth.uid() = user_id);

create index if not exists lancamentos_user_id_idx on public.lancamentos(user_id);
create index if not exists lancamentos_criado_em_idx on public.lancamentos(criado_em desc);
